"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from builtins import (
    bool,
    int,
)
from collections.abc import (
    Iterable,
)
from fr24.proto._common_pb2 import (
    AircraftInfo,
    ExtendedFlightInfo,
    RestrictionVisibility,
    ScheduleInfo,
    TrailPoint,
)
from google.protobuf.descriptor import (
    Descriptor,
    FileDescriptor,
)
from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer,
)
from google.protobuf.message import (
    Message,
)
from typing import (
    Literal,
    final,
)

DESCRIPTOR: FileDescriptor

@final
class PlaybackFlightRequest(Message):
    DESCRIPTOR: Descriptor

    FLIGHT_ID_FIELD_NUMBER: int
    TIMESTAMP_FIELD_NUMBER: int
    RESTRICTION_MODE_FIELD_NUMBER: int
    flight_id: int
    """FR24 Flight ID (e.g. `962788562` = `0x3962fcd2`)"""
    timestamp: int
    """Actual time of departure (ATD) of the historic flight,
    Unix timestamp in seconds.
    """
    restriction_mode: RestrictionVisibility.ValueType
    def __init__(
        self,
        *,
        flight_id: int = ...,
        timestamp: int = ...,
        restriction_mode: RestrictionVisibility.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: Literal["flight_id", b"flight_id", "restriction_mode", b"restriction_mode", "timestamp", b"timestamp"]) -> None: ...

@final
class PlaybackFlightResponse(Message):
    DESCRIPTOR: Descriptor

    AIRCRAFT_INFO_FIELD_NUMBER: int
    SCHEDULE_INFO_FIELD_NUMBER: int
    FLIGHT_INFO_FIELD_NUMBER: int
    FLIGHT_TRAIL_LIST_FIELD_NUMBER: int
    @property
    def aircraft_info(self) -> AircraftInfo: ...
    @property
    def schedule_info(self) -> ScheduleInfo: ...
    @property
    def flight_info(self) -> ExtendedFlightInfo: ...
    @property
    def flight_trail_list(self) -> RepeatedCompositeFieldContainer[TrailPoint]: ...
    def __init__(
        self,
        *,
        aircraft_info: AircraftInfo | None = ...,
        schedule_info: ScheduleInfo | None = ...,
        flight_info: ExtendedFlightInfo | None = ...,
        flight_trail_list: Iterable[TrailPoint] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: Literal["aircraft_info", b"aircraft_info", "flight_info", b"flight_info", "schedule_info", b"schedule_info"]) -> bool: ...
    def ClearField(self, field_name: Literal["aircraft_info", b"aircraft_info", "flight_info", b"flight_info", "flight_trail_list", b"flight_trail_list", "schedule_info", b"schedule_info"]) -> None: ...
