# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fr24/proto/v1.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'fr24/proto/v1.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from fr24.proto import _common_pb2 as fr24_dot_proto_dot___common__pb2
from fr24.proto import _live_feed_pb2 as fr24_dot_proto_dot___live__feed__pb2
from fr24.proto import _debug_pb2 as fr24_dot_proto_dot___debug__pb2
from fr24.proto import _search_index_pb2 as fr24_dot_proto_dot___search__index__pb2
from fr24.proto import _follow_flight_pb2 as fr24_dot_proto_dot___follow__flight__pb2
from fr24.proto import _live_flight_status_pb2 as fr24_dot_proto_dot___live__flight__status__pb2
from fr24.proto import _live_trail_pb2 as fr24_dot_proto_dot___live__trail__pb2
from fr24.proto import _nearest_flights_pb2 as fr24_dot_proto_dot___nearest__flights__pb2
from fr24.proto import _top_flights_pb2 as fr24_dot_proto_dot___top__flights__pb2

from fr24.proto._common_pb2 import *
from fr24.proto._live_feed_pb2 import *
from fr24.proto._debug_pb2 import *
from fr24.proto._search_index_pb2 import *
from fr24.proto._follow_flight_pb2 import *
from fr24.proto._live_flight_status_pb2 import *
from fr24.proto._live_trail_pb2 import *
from fr24.proto._nearest_flights_pb2 import *
from fr24.proto._top_flights_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x66r24/proto/v1.proto\x12\x02v1\x1a\x18\x66r24/proto/_common.proto\x1a\x1b\x66r24/proto/_live_feed.proto\x1a\x17\x66r24/proto/_debug.proto\x1a\x1e\x66r24/proto/_search_index.proto\x1a\x1f\x66r24/proto/_follow_flight.proto\x1a$fr24/proto/_live_flight_status.proto\x1a\x1c\x66r24/proto/_live_trail.proto\x1a!fr24/proto/_nearest_flights.proto\x1a\x1d\x66r24/proto/_top_flights.protoB\x02H\x01P\x00P\x01P\x02P\x03P\x04P\x05P\x06P\x07P\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fr24.proto.v1_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\001'
# @@protoc_insertion_point(module_scope)
